name: buildAstro
on: [push]
jobs:
  build-astro:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./astro
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install 
        run: npm install
      - name: build astro 
        run: npm run build
      - name: Upload generated PDF 
        uses: actions/upload-artifact@v1
        with:
          name: dev-landingpage
          path: astro/dist
